---
addons:
  sonarcloud:
    organization: alevin-github
before_cache:
  - 'rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock'
  - 'rm -rf $HOME/.gradle/caches/*/plugin-resolution/'
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.sonar/cache/
    - $HOME/.m2/repository
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - .gradle
jdk:
  - openjdk11
language: java
script:
  - './gradlew clean assemble --stacktrace'
  - './gradlew sonarqube -Dsonar.projectKey=alevin_SwerveDriveSpark -Dsonar.organization=alevin-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN'
