language: java

jdk:
 - openjdk11
 
branches:
  only:
    - master

addons:
  sonarcloud:
    organization: "alevin-github"

script:
  - git fetch --unshallow
  - ./gradlew clean assemble --stacktrace
  - ./gradlew sonarqube
# - ./gradlew checkstyle lint --stacktrace  
  
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
   directories:
    - "$HOME/.sonar/cache/"  
    - '$HOME/.m2/repository'
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
    - '.gradle'
