language: java
jdk:
 - openjdk11
 
branches:
  only:
    - master

#addons:
#  sonarcloud:
#    organization: "alevin-github"
#
#script:
#  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
