language: java
jdk:
 - openjdk11
 
branches:
  only:
    - master

addons:
  sonarcloud:
    organization: "alevin-github"

script:
  - ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

cache:
  directories:
    - '$HOME/.sonar/cache'
